version: '3'

services:
  db:
    image: bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: feirinhaagroecologica
    ports:
      - 5432:5432
